plugins: fetchart embedart convert scrub lastgenre chroma web
directory: /mnt/usb/music/
library: /mnt/usb/music/library.db
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: no
    log: /tmp/beet.log
